apiVersion: v1
kind: Service
metadata:
  name: {{ template "superset.fullname" . }}-ext
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    app: {{ template "superset.name" . }}
    release: {{ .Release.Name }}