apiVersion: v1
kind: Pod
metadata:
  labels:
    test: readiness
  name: readiness-http
spec:
  restartPolicy: Never
  containers:
  - name: readiness
    image: yauritux/busybox-curl
    args:
    - /bin/sh
    - -c
    - sleep 600
    readinessProbe:
      exec:
        command:
        - curl
        - http://controlcenter:9021
      initialDelaySeconds: 60
      periodSeconds: 10
      timeoutSeconds: 500
      failureThreshold: 50
