apiVersion: v1
kind: Service
metadata:
  name: controlcenter-ext
spec:
  type: NodePort
  selector:
    confluent-platform: 'true'
    type: controlcenter
    app: controlcenter
  ports:
    - port: 9021
      targetPort: 9021
      nodePort: 30002
