apiVersion: v1
kind: Service
metadata:
  name: restproxy-ext
spec:
  type: NodePort
  selector:
    confluent-platform: 'true'
    cr-name: kafkarestproxy
    type: kafkarestproxy
  ports:
    - port: 8088
      targetPort: 8088
      nodePort: 30003
