apiVersion: v1
kind: Service
metadata:
  name: restproxy-ext
spec:
  type: NodePort
  selector:
    confluent-platform: 'true'
    app: kafkarestproxy
    type: kafkarestproxy
  ports:
    - port: 8082
      targetPort: 8082
